openapi: "3.0.2"
info:
  title: "beerbox"
  version: "0.1"
servers:
  - url: "http://example.com/"
    description: "beerbox"
components:
  schemas:
    UserRequest:
      type: "object"
      required:
        - "username"
      properties:
        username:
          type: "string"
    UserResponse:
      type: "object"
      required:
        - "username"
        - "createdAt"
        - "modifiedAt"
      properties:
        username:
          type: "string"
        createdAt:
          type: "string"
          format: "date-time"
        modifiedAt:
          type: "string"
          format: "date-time"
    Check:
      type: "object"
      required:
        - "name"
        - "time"
        - "status"
        - "observedValue"
        - "observedUnit"
      properties:
        name:
          type: "string"
        time:
          type: "string"
          format: "date-time"
        status:
          type: "string"
          enum:
            - "fail"
            - "pass"
        observedValue:
          type: "string"
        observedUnit:
          type: "string"
    HealthResponse:
      type: "object"
      required:
        - "status"
        - "checks"
        - "version"
        - "service"
      properties:
        status:
          type: "string"
          enum:
            - "fail"
            - "pass"
        checks:
          type: "array"
          items:
            $ref: "#/components/schemas/Check"
        version:
          type: "string"
        service:
          type: "string"
    ErrorResponse:
      type: "object"
      properties:
        code:
          type: "string"
        message:
          type: "string"
        data:
          type:
            - "object"
            - "array"
      required:
        - "code"
        - "message"
paths:
  /users:
    get:
      summary: "get users"
      tags:
        - "users"
      description: "Get the list of active users"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/UserResponse"
    post:
      summary: "create user"
      tags:
        - "users"
      description: "Create a new user"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRequest"
      responses:
        "201":
          description: "CREATED"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
        "422":
          description: "Unprocessable Entity"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "409":
          description: "Conflict"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /livez:
    get:
      summary: "get liveness probe"
      tags:
        - "health"
      description: "Get the liveness probe of the applicative server"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
  /readyz:
    get:
      summary: "get the readiness probe"
      tags:
        - "health"
      description: "Get the readiness probe of the applicative server"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
        "503":
          description: "Service Unavailable"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
